# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb325c9c4b59c5b1765b61b0e3f1df62097d0a7539e29797b3f8ab2e0b59313fccecd11c7befec3cbe5839785236c96a2c0d4e091c1e45555aee77ef8501ab05

test:
  secret_key_base: 17f039712e4618b9e48985058dea3836ce88def7c98b106ae4eb751df94ddcdc36d957f5caea1c3168bec1b43d8b2d6e1c372ebe504c0e6eac32f5569cc74e85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
